version: 0.0
os: linux
files:
 - source: ganesh-build/scripts/*
    destination: /home/ec2-user/app/scripts
 - source: ganesh-build/*.jar
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 60
      runas: ec2-user
