version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app

hooks:
  BeforeInstall:
    - location: /home/ec2-user/app/stop_server.sh
      timeout: 60
      runas: ec2-user

  AfterInstall:
    - location: /home/ec2-user/app/install_dependencies.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: /home/ec2-user/app/start_server.sh
      timeout: 60
      runas: ec2-user
