version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/app

hooks:
#  BeforeInstall:
#    - location: ./stop_server.sh
#      timeout: 60
#      runas: ec2-user

  AfterInstall:
    - location: ./install_dependencies.sh
      timeout: 60
      runas: ec2-user

  ApplicationStart:
    - location: ./start_server.sh
      timeout: 60
      runas: ec2-user
