version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Building the JAR...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed.
      - cp target/*.jar ./
      - cp appspec.yaml ./
      - mkdir -p scripts
      - cp scripts/*.sh scripts/
      - chmod +x scripts/*.sh

artifacts:
  files:
    - '**/*'
