version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Building the JAR...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed.
      - mkdir -p build-output
      - cp target/*.jar build-output/
      - cp springwithstaticapplication/appspec.yaml build-output/
      - cp -r scripts build-output/

artifacts:
  files:
    - build-output/**/*
  discard-paths: yes
