version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven

  pre_build:
    commands:
      - echo Cleaning project...
      - mvn clean

  build:
    commands:
      - echo Building the JAR...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed.
      - mkdir -p build-output/scripts
      - cp target/*.jar build-output/
      - cp appspec.yaml build-output/
      - cp scripts/*.sh build-output/scripts/
      - chmod +x build-output/scripts/*.sh

artifacts:
  base-directory: build-output
  files:
    - '**/*'
