version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17  
    commands:
      - echo Installing Maven...
      - yum update -y
      - yum install -y maven

  pre_build:
    commands:
      - echo Running Maven clean
      - mvn clean

  build:
    commands:
      - echo Building the project...
      - mvn package -DskipTests

  post_build:
    commands:
      - echo Build completed successfully.

artifacts:
  files:
    - target/*.jar  
