options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET

steps:
    id: Run Maven build
  - name: gcr.io/cloud-builders/mvn
    entrypoint: bash
    args:
      - -c
      - |
        echo "🧪 Running Maven build...."
        mvn clean install
        echo "✅ Build complete!"

    id: Build Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_GAN_WEB_REPO_PATH}${_SERVICE_NAME}:${_IMAGE_TAG}
      - .

    id: Push Docker image
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_GAN_WEB_REPO_PATH}${_SERVICE_NAME}:${_IMAGE_TAG}
