service:
  name: my-cloud-run-service
  port: 7000

image:
  repository: us-central1-docker.pkg.dev/polished-core-463907-m5/frontend/frontend
  tag: latest

resources:
  cpu: 1
  memory: 512Mi

cloudRun:
  region: us-central1
  platform: managed
  allowUnauthenticated: true
